### ISSUE TITLE
按步骤做的，日志里遇到了Connection refused的问题，请问是什么原因？

### ISSUE THREAD

**Issue by Gshelterm** [EOSLaoMao/eos-cluster-generator#8]
docker容器：
~/eos-cluster-generator$ sudo docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                                            NAMES
f20ad85ef7ee        eoslaomao/eos:1.4.1-blacklist-plugin   "nodeos --config /op…"   3 minutes ago       Up 3 minutes        0.0.0.0:8874->8874/tcp, 0.0.0.0:9874->9874/tcp   nodeosd1
36a2fb7f945b        eoslaomao/eos:1.4.1-blacklist-plugin   "nodeos --config /op…"   3 minutes ago       Up 3 minutes        0.0.0.0:8873->8873/tcp, 0.0.0.0:9873->9873/tcp   nodeosd2
019c2a6df20c        eoslaomao/eos:1.4.1-blacklist-plugin   "nodeos --config /op…"   3 minutes ago       Up 3 minutes        0.0.0.0:8888->8888/tcp, 0.0.0.0:9876->9876/tcp   nodeosd
dbef8740584a        eoslaomao/eos:1.4.1-blacklist-plugin   "nodeos --config /op…"   3 minutes ago       Up 3 minutes        0.0.0.0:8875->8875/tcp, 0.0.0.0:9875->9875/tcp   nodeosd0

执行docker logs -f nodeosd， nodeosd的日志：
info  2019-03-12T03:05:22.821 thread-0  net_plugin.cpp:1921           connect              ] host: 127.0.0.1 port: 9875
info  2019-03-12T03:05:22.821 thread-0  net_plugin.cpp:1921           connect              ] host: 127.0.0.1 port: 9874
info  2019-03-12T03:05:22.821 thread-0  net_plugin.cpp:1921           connect              ] host: 127.0.0.1 port: 9873
error 2019-03-12T03:05:22.821 thread-0  net_plugin.cpp:1963           operator()           ] connection failed to 127.0.0.1:9875: Connection refused
error 2019-03-12T03:05:22.821 thread-0  net_plugin.cpp:1963           operator()           ] connection failed to 127.0.0.1:9874: Connection refused
error 2019-03-12T03:05:22.821 thread-0  net_plugin.cpp:1963           operator()           ] connection failed to 127.0.0.1:9873: Connection refused

**Comment by Gshelterm** [comment]
docker-compose.yaml:

`
version: "3"

services:
  nodeosd:
    image: eoslaomao/eos:1.4.1-blacklist-plugin
    command: nodeos --config /opt/eosio/bin/data-dir/config.ini -d /opt/eosio/bin/data-dir --genesis-json /opt/eosio/bin/data-dir/genesis.json --contracts-console
    hostname: nodeosd
    container_name: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "9876"
    volumes:
      - ./data/bios-node:/opt/eosio/bin/data-dir
  nodeosd0:
    image: eoslaomao/eos:1.4.1-blacklist-plugin
    command: nodeos --config /opt/eosio/bin/data-dir/config.ini -d /opt/eosio/bin/data-dir --genesis-json /opt/eosio/bin/data-dir/genesis.json --contracts-console
    hostname: nodeosd
    container_name: nodeosd0
    ports:
      - 9875:9875
      - 8875:8875
    expose:
      - "9875"
      - "8875"
    volumes:
      - ./data/eos-bp0/:/opt/eosio/bin/data-dir
  nodeosd1:
    image: eoslaomao/eos:1.4.1-blacklist-plugin
    command: nodeos --config /opt/eosio/bin/data-dir/config.ini -d /opt/eosio/bin/data-dir --genesis-json /opt/eosio/bin/data-dir/genesis.json --contracts-console
    hostname: nodeosd
    container_name: nodeosd1
    ports:
      - 9874:9874
      - 8874:8874
    expose:
      - "9874"
      - "8874"
    volumes:
      - ./data/eos-bp1/:/opt/eosio/bin/data-dir
  nodeosd2:
    image: eoslaomao/eos:1.4.1-blacklist-plugin
    command: nodeos --config /opt/eosio/bin/data-dir/config.ini -d /opt/eosio/bin/data-dir --genesis-json /opt/eosio/bin/data-dir/genesis.json --contracts-console
    hostname: nodeosd
    container_name: nodeosd2
    ports:
      - 9873:9873
`

**Comment by WLBF** [comment]
This problem is caused by incorrct peer ip setting from the init script. you can notice that all nodes are trying to connect its localhost:
```
nfo 2019-03-12T03:05:22.821 thread-0 net_plugin.cpp:1921 connect ] host: 127.0.0.1 port: 9875
info 2019-03-12T03:05:22.821 thread-0 net_plugin.cpp:1921 connect ] host: 127.0.0.1 port: 9874
info 2019-03-12T03:05:22.821 thread-0 net_plugin.cpp:1921 connect ] host: 127.0.0.1 port: 9873
```

The solution is configuring the host machine ip manually, make sure all nodes have correct peer ip settings.
modify this file: https://github.com/EOSLaoMao/eos-cluster-generator/blob/master/config.py#L2

e.g.
```
import socket
#IP = socket.gethostbyname(socket.gethostname())
IP = "192.168.86.20"
```

**Comment by Gshelterm** [comment]
@WLBF Thank you for your reply. Didn't realize it's the mechanism of docker container.
I have set IP = "real IP address" in config.py, and nodes looks are producing blocks and recieve blocks， but still encountered  a  problem: 
 “Connection reset by peer” repeats showing  in logs at intervals, but testnet is running properly(recieve or produce blocks from bpa/bp1/bp2)，why there will be a network problem?
The following use "192.168.86.20" indicate IP

eg. docker logs -f nodeosd1
```
info  2019-03-13T07:40:47.504 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 73f9006b7c42be58... #1620 @ 2019-03-13T07:40:47.500 signed by bpa [trxs: 0, lib: 1572, conf: 0, latency: 4 ms]
info  2019-03-13T07:40:48.001 thread-0  producer_plugin.cpp:1490      produce_block        ] Produced block 00000655dbff0190... #1621 @ 2019-03-13T07:40:48.000 signed by bp1 [trxs: 0, lib: 1584, confirmed: 24]
info  2019-03-13T07:40:48.500 thread-0  producer_plugin.cpp:1490      produce_block        ] Produced block 000006564476e8c8... #1622 @ 2019-03-13T07:40:48.500 signed by bp1 [trxs: 0, lib: 1584, confirmed: 0]
info  2019-03-13T07:40:48.518 thread-0  net_plugin.cpp:1921           connect              ] host: 192.168.86.20 port: 9875
error 2019-03-13T07:40:48.520 thread-0  net_plugin.cpp:2140           operator()           ] Error reading message from 192.168.86.20:9875: Connection reset by peer
info  2019-03-13T07:40:49.000 thread-0  producer_plugin.cpp:1490      produce_block        ] Produced block 00000657a46f19eb... #1623 @ 2019-03-13T07:40:49.000 signed by bp1 [trxs: 0, lib: 1584, confirmed: 0]
info  2019-03-13T07:40:49.500 thread-0  producer_plugin.cpp:1490      produce_block        ] Produced block 00000658c455481b... #1624 @ 2019-03-13T07:40:49.500 signed by bp1 [trxs: 0, lib: 1584, confirmed: 0]
```
docker logs -f nodeosd
```
info  2019-03-13T07:51:17.501 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block f9695cf14ccf8d93... #2880 @ 2019-03-13T07:51:17.500 signed by bpa [trxs: 0, lib: 2832, conf: 0, latency: 1 ms]
info  2019-03-13T07:51:18.003 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block f5c3f1a0c5bb45b0... #2881 @ 2019-03-13T07:51:18.000 signed by bp1 [trxs: 0, lib: 2844, conf: 24, latency: 3 ms]
info  2019-03-13T07:51:18.240 thread-0  net_plugin.cpp:1921           connect              ] host: 192.168.86.20 port: 9874
error 2019-03-13T07:51:18.241 thread-0  net_plugin.cpp:2140           operator()           ] Error reading message from 192.168.86.20:9874: Connection reset by peer
info  2019-03-13T07:51:18.501 thread-0  producer_plugin.cpp:337       on_incoming_block    ] Received block 2217adb4da0b1bee... #2882 @ 2019-03-13T07:51:18.500 signed by bp1 [trxs: 0, lib: 2844, conf: 0, latency: 1 ms]
```
also with nodeosd0, nodeosd2
```
~/eos-cluster-generator/data$ sudo docker ps
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                                            NAMES
8d0f0a579e14        eoslaomao/eos:1.4.1-blacklist-plugin   "nodeos --config /op…"   44 minutes ago      Up 44 minutes       0.0.0.0:8874->8874/tcp, 0.0.0.0:9874->9874/tcp   nodeosd1
d59578754695        eoslaomao/eos:1.4.1-blacklist-plugin   "nodeos --config /op…"   44 minutes ago      Up 44 minutes       0.0.0.0:8873->8873/tcp, 0.0.0.0:9873->9873/tcp   nodeosd2
c699eff0e438        eoslaomao/eos:1.4.1-blacklist-plugin   "nodeos --config /op…"   44 minutes ago      Up 44 minutes       0.0.0.0:8888->8888/tcp, 0.0.0.0:9876->9876/tcp   nodeosd
36ef96d3a834        eoslaomao/eos:1.4.1-blacklist-plugin   "nodeos --config /op…"   44 minutes ago      Up 44 minutes       0.0.0.0:8875->8875/tcp, 0.0.0.0:9875->9875/tcp   nodeosd0
```
